### ISSUE TITLE
VATSIM integration broke OPRF radar.

### ISSUE THREAD

**Issue by JMaverick16** [JMaverick16/KC-137R#9]
@FirstOfficerDelta apparently your commits for VATSIM integration have broken the existing radar.

**Comment by FirstOfficerDelta** [comment]
Oh dear, what exactly broke?

Sorry, it has been quite some time since I made edits to the KC-137 radar.

**Comment by JMaverick16** [comment]
Apparently the AWACS radar screen stopped working after your commits, @NikolaiVChr found the bug but I don't really know when or which commit breaks it.

**Comment by FirstOfficerDelta** [comment]
Alright, I will try to see what is wrong.

**Comment by JMaverick16** [comment]
Appreciated!

**Comment by FirstOfficerDelta** [comment]
Hmmmm...okay, I see what NikolaiVChr means, the MP radar is not detecting any aircraft...it must be the mps.xml.

**Comment by NikolaiVChr** [comment]
added1291242bcc12bd43b7009c6acd9ec0c4800 broke the radar

**Comment by FirstOfficerDelta** [comment]
Okay, so I removed VATSIM Integration and reduced the aircraft count back to 20 in my latest commit but it seems that something else is broken.

I tried checking the back of the radar screen with a distance of 400nmi, with mixed of MP and AI traffic, and I saw that the radar is working at the back, but you can't see it at the front:
![image](https://user-images.githubusercontent.com/66116718/156873037-0ec59311-0cdf-411f-ac24-ae45b3fc10c6.png)

**Comment by FirstOfficerDelta** [comment]
Yep, I got it fixed...hopefully. Turns out it was just a 3D modelling issue in the mps.ac. Just had to flip the normals and do some delete and copying and yeah: 
![image](https://user-images.githubusercontent.com/66116718/167258668-6ab36242-aaaa-4542-98d9-748982b424ac.png)


The image is showing MP and AI traffic.

**Comment by NikolaiVChr** [comment]
The last pull request #15 will fix this for good for E-3R.
Will also delete all the old property based radar and replace it with a nasal radar that supports VATSIM too.
